#!/usr/bin/bash
#wget Mirror List
curl -O https://raw.githubusercontent.com/benasanders/ArchMBPScripts/master/mirrorlist
cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.backup
cp mirrorlist /etc/pacman.d/mirrorlist
timedatectl set-ntp true
mkfs.ext4 /dev/sda4
e2label /dev/sda4 Arch
mount /dev/sda4 /mnt
mkdir /mnt/boot
mount /dev/sda1 /mnt/boot
pacstrap /mnt base
genfstab -L /mnt >> /mnt/etc/fstab
echo "edit fstab to"
echo "defaults,noatime,discard"
echo "Then change root and continue to 2"
echo "arch-chroot /mnt"
