#!/bin/bash
systemctl restart dhcpcd
sleep 15
git clone https://aur.archlinux.org/package-query.git
cd package-query
makepkg -si
cd ..
git clone https://aur.archlinux.org/yaourt.git
cd yaourt
makepkg -si
cd ..
yaourt --noconfirm -S google-chrome bcwc-pcie-git broadcom-wl mbpfan-git spotify pepper-flash ttf-ms-fonts sublime-text-dev remmina-git remmina-plugin-rdesktop
echo "Now reboot and login AS ROOT"
