#!/bin/bash
systemctl restart dhcpcd
sleep 15
#wget mbpfan config
wget https://raw.githubusercontent.com/benasanders/ArchMBPScripts/master/mbpfan.conf
#wget powertop.service
wget https://raw.githubusercontent.com/benasanders/ArchMBPScripts/master/powertop.service
#wget cpupower
wget https://raw.githubusercontent.com/benasanders/ArchMBPScripts/master/cpupower
#wget sddm pam file
wget https://raw.githubusercontent.com/benasanders/ArchMBPScripts/master/sddm
cp powertop.service /etc/systemd/system/powertop.service
cp mbpfan.conf /etc/mbpfan.conf
echo "noarp" >> /etc/dhcpcd.conf
echo "facetimehd" >> /ect/modules
systemctl enable mbpfan.service
systemctl disable dhcpcd
systemctl enable sddm
systemctl enable cpupower
systemctl enable powertop.service
systemctl enable NetworkManager.service
cp cpupower /etc/default/cpupower
cp sddm /etc/pam.d/sddm
echo "vm.swappiness=1" >> /etc/sysctl.d/99-sysctl.conf
sysctl vm.swappiness=1
echo "options snd_hda_intel power_save=1" >> /etc/modprobe.d/60-snd_hda_intel.conf
echo "options i915 enable_rc6=1 enable_fbc=1 lvds_downclock=1" >> /etc/modprobe.d/60-i915.conf
echo "options usbcore autosuspend=1" >> /etc/modprobe.d/usbcore.conf
echo "Now reboot to a hopefully working system"
